//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnetforum.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class various {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal various() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aspnetforum.Resources.various", typeof(various).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to this forum is restricted.
        /// </summary>
        public static string AccessToForumDenied {
            get {
                return ResourceManager.GetString("AccessToForumDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your forum registration by clicking the link below..
        /// </summary>
        public static string ActivationEmailBody {
            get {
                return ResourceManager.GetString("ActivationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate your membership..
        /// </summary>
        public static string ActivationEmailSubject {
            get {
                return ResourceManager.GetString("ActivationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Not activated - wrong code or username.
        /// </summary>
        public static string ActivationError {
            get {
                return ResourceManager.GetString("ActivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation successful. You are welcome to login.
        /// </summary>
        public static string ActivationSuccess {
            get {
                return ResourceManager.GetString("ActivationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add an option.
        /// </summary>
        public static string AddAnOption {
            get {
                return ResourceManager.GetString("AddAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add message.
        /// </summary>
        public static string AddMessage {
            get {
                return ResourceManager.GetString("AddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new forum:.
        /// </summary>
        public static string AddNewForum {
            get {
                return ResourceManager.GetString("AddNewForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to another file....
        /// </summary>
        public static string AnotherFile {
            get {
                return ResourceManager.GetString("AnotherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attach files.
        /// </summary>
        public static string AttachFiles {
            get {
                return ResourceManager.GetString("AttachFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments:.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀ back to the website.
        /// </summary>
        public static string BackToWebSite {
            get {
                return ResourceManager.GetString("BackToWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a poll.
        /// </summary>
        public static string CreateAPoll {
            get {
                return ResourceManager.GetString("CreateAPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled users.
        /// </summary>
        public static string DisabledUsers {
            get {
                return ResourceManager.GetString("DisabledUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled users.
        /// </summary>
        public static string EnabledUsers {
            get {
                return ResourceManager.GetString("EnabledUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The avatar file size is too big.
        /// </summary>
        public static string ErrorBigAvatar {
            get {
                return ResourceManager.GetString("ErrorBigAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture dimensions are too big.
        /// </summary>
        public static string ErrorBigPictureDimensions {
            get {
                return ResourceManager.GetString("ErrorBigPictureDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users are not allowed to change theirs usernames when Integrated authentication is ON.
        /// </summary>
        public static string ErrorIntegratedUserName {
            get {
                return ResourceManager.GetString("ErrorIntegratedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a picture file.
        /// </summary>
        public static string ErrorNotPictureFile {
            get {
                return ResourceManager.GetString("ErrorNotPictureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords do not match..
        /// </summary>
        public static string ErrorPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &lt;b&gt;{0}&lt;/b&gt; already exists..
        /// </summary>
        public static string ErrorUserExists {
            get {
                return ResourceManager.GetString("ErrorUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is wrong..
        /// </summary>
        public static string ErrorWrongOldPassword {
            get {
                return ResourceManager.GetString("ErrorWrongOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everywhere.
        /// </summary>
        public static string Everywhere {
            get {
                return ResourceManager.GetString("Everywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum category:.
        /// </summary>
        public static string ForumCategory {
            get {
                return ResourceManager.GetString("ForumCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string Guests {
            get {
                return ResourceManager.GetString("Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage:.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logon date.
        /// </summary>
        public static string LastLogonDate {
            get {
                return ResourceManager.GetString("LastLogonDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest post.
        /// </summary>
        public static string LatestPost {
            get {
                return ResourceManager.GetString("LatestPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong username/password.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost password.
        /// </summary>
        public static string LostPassword {
            get {
                return ResourceManager.GetString("LostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You or someone else asked for a {0} forum password recovery.
        ///
        ///Username: {1}
        ///Your NEW Password: {2}
        ///
        ///{3}.
        /// </summary>
        public static string LostPasswordEmailBody {
            get {
                return ResourceManager.GetString("LostPasswordEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually adding a user.
        /// </summary>
        public static string ManuallyAddingUser {
            get {
                return ResourceManager.GetString("ManuallyAddingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to add a new user manually, without requiring a user to go through the registration process.
        /// </summary>
        public static string ManuallyAddingUserDescription {
            get {
                return ResourceManager.GetString("ManuallyAddingUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max attachment size.
        /// </summary>
        public static string MaxAttachSize {
            get {
                return ResourceManager.GetString("MaxAttachSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min ago.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more smilies.
        /// </summary>
        public static string MoreSmilies {
            get {
                return ResourceManager.GetString("MoreSmilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new personal message(s).
        ///
        ///To view the updates visit.
        /// </summary>
        public static string NewPersonalEmailBody {
            get {
                return ResourceManager.GetString("NewPersonalEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum notification. New personal message..
        /// </summary>
        public static string NewPersonalSubject {
            get {
                return ResourceManager.GetString("NewPersonalSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new private messages.
        /// </summary>
        public static string NewPrivateMsgs {
            get {
                return ResourceManager.GetString("NewPrivateMsgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are subscribed to a forum, a new topic is created..
        /// </summary>
        public static string NewThreadEmailBody {
            get {
                return ResourceManager.GetString("NewThreadEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum notification. New topic in a forum..
        /// </summary>
        public static string NewThreadEmailSubject {
            get {
                return ResourceManager.GetString("NewThreadEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new topic.
        /// </summary>
        public static string NewTopic {
            get {
                return ResourceManager.GetString("NewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No forums have been created yet. Contact the forum administrator..
        /// </summary>
        public static string NoForums {
            get {
                return ResourceManager.GetString("NoForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No forums found..
        /// </summary>
        public static string NoForumsFound {
            get {
                return ResourceManager.GetString("NoForumsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when a reply is posted.
        /// </summary>
        public static string NotifyMeOnReply {
            get {
                return ResourceManager.GetString("NotifyMeOnReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online users.
        /// </summary>
        public static string OnlineUsers {
            get {
                return ResourceManager.GetString("OnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or enter a new value:.
        /// </summary>
        public static string OrEnterNew {
            get {
                return ResourceManager.GetString("OrEnterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages:.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please login or &lt;a href=&quot;register.aspx&quot;&gt;register&lt;/a&gt; to create a topic.
        /// </summary>
        public static string PleaseLoginRegisterToCreateTopic {
            get {
                return ResourceManager.GetString("PleaseLoginRegisterToCreateTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll option.
        /// </summary>
        public static string PollOption {
            get {
                return ResourceManager.GetString("PollOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll Question.
        /// </summary>
        public static string PollQuestion {
            get {
                return ResourceManager.GetString("PollQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous messages in the topic:.
        /// </summary>
        public static string PreviousMessagesInTopic {
            get {
                return ResourceManager.GetString("PreviousMessagesInTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile saved.
        /// </summary>
        public static string ProfileSaved {
            get {
                return ResourceManager.GetString("ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psw:.
        /// </summary>
        public static string Psw {
            get {
                return ResourceManager.GetString("Psw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent posts.
        /// </summary>
        public static string RecentPosts {
            get {
                return ResourceManager.GetString("RecentPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent topics.
        /// </summary>
        public static string RecentTopics {
            get {
                return ResourceManager.GetString("RecentTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered since.
        /// </summary>
        public static string RegisteredSince {
            get {
                return ResourceManager.GetString("RegisteredSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bull; reply with quote.
        /// </summary>
        public static string ReplyWithQuote {
            get {
                return ResourceManager.GetString("ReplyWithQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds ago.
        /// </summary>
        public static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a category from this list:.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a private message.
        /// </summary>
        public static string SendAPrivateMessage {
            get {
                return ResourceManager.GetString("SendAPrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smilies.
        /// </summary>
        public static string Smilies {
            get {
                return ResourceManager.GetString("Smilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop watching this forum for &lt;b&gt;topics&lt;/b&gt;.
        /// </summary>
        public static string StopWatchingForum {
            get {
                return ResourceManager.GetString("StopWatchingForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop watching this forum for &lt;b&gt;posts&lt;/b&gt;.
        /// </summary>
        public static string StopWatchingForumPosts {
            get {
                return ResourceManager.GetString("StopWatchingForumPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Forums.
        /// </summary>
        public static string SubForums {
            get {
                return ResourceManager.GetString("SubForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        public static string Threads {
            get {
                return ResourceManager.GetString("Threads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are subscribed to a discussion thread, which has been updated..
        /// </summary>
        public static string ThreadUpdatedEmailBody {
            get {
                return ResourceManager.GetString("ThreadUpdatedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum notification. Thread updated..
        /// </summary>
        public static string ThreadUpdatedEmailSubject {
            get {
                return ResourceManager.GetString("ThreadUpdatedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unread topics.
        /// </summary>
        public static string UnreadTopics {
            get {
                return ResourceManager.GetString("UnreadTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user:.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists!.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found or you are not logged in.
        /// </summary>
        public static string UserNotFoundOrYouLoggedOut {
            get {
                return ResourceManager.GetString("UserNotFoundOrYouLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users online.
        /// </summary>
        public static string UsersOnline {
            get {
                return ResourceManager.GetString("UsersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully created!.
        /// </summary>
        public static string UserSuccessfullyCreated {
            get {
                return ResourceManager.GetString("UserSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watch this forum for new &lt;b&gt;posts&lt;/b&gt;.
        /// </summary>
        public static string WatchForPosts {
            get {
                return ResourceManager.GetString("WatchForPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watch this forum for new &lt;b&gt;topics&lt;/b&gt;.
        /// </summary>
        public static string WatchForTopics {
            get {
                return ResourceManager.GetString("WatchForTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the forums.
        /// </summary>
        public static string WelcomeEmailBody {
            get {
                return ResourceManager.GetString("WelcomeEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our forums. Your account have been activated, please feel free to visit the forum:.
        /// </summary>
        public static string WelcomeEmailSubject {
            get {
                return ResourceManager.GetString("WelcomeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s going on.
        /// </summary>
        public static string WhatsGoingOn {
            get {
                return ResourceManager.GetString("WhatsGoingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrote.
        /// </summary>
        public static string Wrote {
            get {
                return ResourceManager.GetString("Wrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have.
        /// </summary>
        public static string YouHave {
            get {
                return ResourceManager.GetString("YouHave", resourceCulture);
            }
        }
    }
}
